language: java
after_success:
- mvn deploy --settings settings.xml -DskipTests=true -B
env:
  global:
  - SONATYPE_USERNAME=rkazokas
  - secure: Cyr/lgSkXKS6besmHq78cNf2P7eyc1tALvJHvtKSPqOm/cpMRHtRFvvf3Donmle9RnR5xQKJz49QXc3ybbiUbV5T4aSLYLg4PjEWIE/dhLg7ybdm/mJ2bAYHou3I0s/Uvi4vjKL+4AIwKDZZXsV6+au2CasHVTzSPhDuBPkpaEhTrZaYv2rlWyxr6EmP4AiT4bJPspHZiu8YdEVCwi2nCwHFK+fi4Rlni3m0c8b2fO+wahSDpcLiEliIDIFzOmXEz+WWgrm3KXgbOSwcRNTWR6UySGNKVyO+zcM95pFzdvghMcT3Z5l8Wh7fCl/fBZK1DunIjQGOpSxNsq1fiENpuJXHBF9ixe3qO69Pyg5ZCnGBSoOc4VUVEPfmm9rZremPmqwxa3hZf6pQAqCDVl/suCROR3HnEa7AprCo+Xz36vsaXW57FqDN4Y+LkfVK9pFu8PN3VGZBU6uikdrZABqpbBydQgKxL+e/H3kOb0omuXQ+ur7PqYlBAjSpZZVpv9v4ICpCRE5LB6lCtt5GDbS+fYL1GlsQgUixiPhNySistAVX2jcOynoOI1rGBaAPkktyWeq7iv3YK0qFR3gCCIqTeWu6DyV/Du1Pz+5KcIUyScYL+gGmSx9HVp1X+QTFtdd6VBiK91+c3LksnklBQWQCHmO3NAf7ZUB5hc6SlAGuIUM=
